### ISSUE TITLE
classesStyles properties don't override baseFontStyle properties

### ISSUE THREAD

**Issue by yamov** [archriss/react-native-render-html#102]
`classesStyles` properties override the corresponding `baseFontStyle` properties **only** if the tagsStyles have the same properties. 

For example:

```javascript
<HTML
    html={'Just text <p>Normal paragraph</p><p class="smallRedFont">Small red paragraph</p>'}
    baseFontStyle={{ fontSize: 20, color: 'green' }}
    tagsStyles={{ p: { lineHeight: 30 } }}
    classesStyles={{ smallRedFont: { fontSize: 10, color: 'red' } }}       
 />
```

`fontSize` and `color` properties of `smallRedFont` class **won't** override `fontSize` and `color` of `baseFontStyle`, because `tagsStyles` for `p` **doesn't** include these properties.

In this case, however,

```javascript
<HTML
    html={'Just text <p>Normal paragraph</p><p class="smallRedFont">Small red paragraph</p>'}
    baseFontStyle={{ fontSize: 20, color: 'green' }}
    tagsStyles={{ p: { fontSize: 16, color: 'blue' } }}
    classesStyles={{ smallRedFont: { fontSize: 10, color: 'red' } }}       
 />
```
`fontSize` and `color` properties of `smallRedFont` class **will** override `fontSize` and `color` of `baseFontStyle`, because `tagsStyles` for `p` **does** have these properties.

**Comment by Exilz** [comment]
Hi, thanks for the very precise explanation and reproduction of this issue.

Could you try replacing the line 444 from `HTML.js`

from : 

```javascript
const textElementStyles = this.filterBaseFontStyles(element, classStyles, props);
```

to

```javascript
const textElementStyles = parentTag && TEXT_TAGS.indexOf(parentTag) !== -1 ? {} : this.filterBaseFontStyles(element, classStyles, props);
```

Basically, what I've done here is not to apply `baseFontStyle` to text nodes nested inside other text nodes, since the parent should be the one receiving the style anyway.

I'm pretty concerned with regressions, and the demo isn't complete enough for me to check all use cases. I'd like you to tell me if it fixed it for you, and if you see any potential drawbacks.

**Comment by yamov** [comment]
Hey, @Exilz

Your solution doesn't seem to work properly :/.
It solves the case of `classesStyles` but breaks some other cases. Namely, seems like `baseFontStyle ` does not apply to tags (without classes) anymore.

**Comment by Exilz** [comment]
@yamov @fvsch

Allright, so I took some more time to dig into this problem, which seems closely tied to #119 and it's way more complicated than what I originally thought.

*I think* the whole logic of text style inheritance needs to be rewritten, `filterBaseFontStyle` and those `overridenFrom...` variables just don't cut it.

Here's the logic I came up with that I need to try out :

- **DON'T** apply any styling to the text nodes that aren't mapped as `rawtext`, only compute the final styles for each rawtexts. This just seems easier overall.
- For each `rawtext`, recursively loop from the deepest text parent to the highest.
- Create an empty object that will receive the final text styles for this `rawtext`
- On each iteration, create a style object with the proper priority order : `htmlAttribs` > `classesStyles.class` > `tagsStyles.tag` > `baseFontStyle`
- Only merge the keys that aren't yet applied to the final object. ie: if `fontSize` is already set in the first iteration, ignore the `fontSize` that we got from the 3rd iteration because of a class for instance.

Let's take this snippet as an example :

```html
<p>
    Texte paragraphe
    <span class="red-p">red span </span>
    <span class="blue-p">
         blue<em> span</em>
    </span>
</p>
```

And those props : 

```javascript
            baseFontStyle: { fontSize: 20, color: 'green' },
            classesStyles: {
                'red-p': { fontSize: 10, color: 'red' },
                'blue-p': { fontSize: 10, color: 'blue' }
            }
```

If I'm not mistaken, the above algorithm should map this HTML to the following native components : 

```javascript
                <Text paragraph>
                    <Text raw style={{ fontSize: 20, color: 'green' }}>Texte paragraphe</Text>
                    <Text span>
                        <Text raw style={{ fontSize: 10, color: 'red' }}>red span</Text>
                    </Text>
                    <Text span>
                        <Text raw style={{ fontSize: 10, color: 'blue' }}>blue</Text>
                        <Text em>
                            <Text raw style={{ fontSize: 10, color: 'blue', fontStyle: 'italic' }}>span</Text>
                        </Text>
                    </Text>
                </Text>
```

![](https://puu.sh/zNLRY/77d7738fa8.png)

I'll try to implement this and keep you posted.

**Comment by Exilz** [comment]
A first version of these changes is available for testing in the development branch. I'm looking forward to your feedback.

**Comment by fvsch** [comment]
Thanks, I’ll take a look on monday.

**Comment by CarstenHoyer** [comment]
@Exilz I had a related problem using version 3.9.1. fontSize would not apply, when I was using classesStyles. Here is a test to reproduce it:

The test branch works:
"react-native-render-html": "https://github.com/archriss/react-native-render-html#2fc1f8af99aeb76df1e5816a1d629b27058606ad",

```
const alterNode = (node) => {
    if (node.name === 'p' && !node.parent) {
      node.attribs.class = 'blue-p'
    }
  }

  return (
    <HTML
      baseFontStyle={{ fontSize: 20, color: 'green' }}
      alterNode={alterNode}
      classesStyles={{
        'blue-p': { fontSize: 100, color: 'blue' }
      }}
      html={`<p>Testing</p>`}
    />
  )

**Comment by theill** [comment]
I've tested this as well and the dev branch works nicely for me.
