### ISSUE TITLE
Support <pre> tag

### ISSUE THREAD

**Issue by leoyb** [archriss/react-native-render-html#168]
HTML contains the insert code, like this:
<img width="774" alt="wx20180707-182242 2x" src="https://user-images.githubusercontent.com/10185166/42409868-e061d992-8212-11e8-951e-ce62d1fee843.png">
the source code of this html is a "pre" tag,  i render this HTML into native views by react-native-render-html, i got this result

<img width="428" alt="wx20180707-182310 2x" src="https://user-images.githubusercontent.com/10185166/42409871-e7c13be2-8212-11e8-8c48-698b94fd3398.png">

the render result is unfriendly, the original format is lost. i think render a HTML page which contains insert code is very common and important requirements. so i mentioned this issue, hoping to get a good answer.
## Environment
```js
    React: 16.3.1
    React native: 0.53.0
    react-native-render-html: 3.10.0
```

**Comment by bobjflong** [comment]
Has anyone written a custom renderer, or used one of the other props, to get `pre` tags to display correctly? I haven't managed it yet.

**Comment by ayushnawani** [comment]
@bobjflong  did you get any solution for this? I am also looking way to use pre tag.

**Comment by bobjflong** [comment]
We managed to get this working by substituting newlines within pres using the `alterData` hook, then writing a custom renderer for `pre` that splits these newlines back in:

Step 1. replace newlines within pre text (not exact code):

```javascript
alterData: node => {
  if (node.parent && node.parent.name === "pre") {
    return node.data.replace(/\n/g, "___PRE_NEWLINE___")
  }
}
```

Step 2. add the newlines back in with a custom renderer for pre:

```javascript
const Pre = (_htmlAttribs, _children, _convertedCssStyles, passProps) => {
  const children = passProps.rawChildren
    .map(rawChild => rawChild.data)
    .join("")
    .split("___PRE_NEWLINE___")
  return (
    <React.Fragment key={passProps.key}>
      {children.map(line => (
        <YourMonospaceComponent>
          {line}
        </YourMonospaceComponent>
      ))}
    </React.Fragment>
  )
}
```

Hope that helps

**Comment by Exilz** [comment]
This is now supported in `v4.1.0`

**Comment by Milrer** [comment]
Hello,
Is the functionality still there in the latest version? I'm trying to format my <pre> tags but I get the same result as the author.

**Comment by jsamr** [comment]
@Milrer Should be working in versions 5.1.0 and 6.x (#430). Would you mind providing a snack reproducing your issue?

**Comment by Milrer** [comment]
@jsamr Of course with pleasure : [](https://snack.expo.io/@milrer/spunky-blueberries)

Maybe I've missed something entirely?

I'd rather not upgrade to v6 for production at this time if possible.

**Comment by jsamr** [comment]
@Milrer The renderer is confused by the embedding of `<code>` inside `<pre>` (see https://snack.expo.io/@jsamr/rnrh-pre). It works in browsers because `white-space: pre` rule is inheritable, so `code` should inherit it. But the v5 doesn't support `white-space` CSS rules. Instead, there is a hard-coded exception: https://github.com/meliorence/react-native-render-html/blob/d4a550ca9869fcf2262d5905bacdb8042d1d1baf/src/HTMLUtils.js#L358

v6 has no such problems since it supports white-space rules and CSS inheritance.

**Comment by Milrer** [comment]
Indeed with v6, it works wonderfully well.
Your work is really crazy, I think you can't imagine how much what you offer helps thousands and thousands of developers, thank you!

Maybe you have an idea for syntax highlighting of the code?

**Comment by jsamr** [comment]
@Milrer Thank you so much for the feedback, it really makes a difference :heart:

> Maybe you have an idea for syntax highlighting of the code?

Well, yes! I'm preparing a v6 demo which will also acts as a "discovery" app. And I needed a fast syntax highlighter, since `react-native-syntax-highlight` is pretty slow. So I made one, but it's still unpublished. However, You can find it in the tree here: https://github.com/meliorence/react-native-render-html/blob/feat/substratum/demo/src/highlight/Highlighter.tsx

**Comment by Milrer** [comment]
@jsamr Oh that's great! Can't wait to get this published, thanks for the work!
