### ISSUE TITLE
How to judge the content is loaded, including images

### ISSUE THREAD

**Issue by duansiyu** [archriss/react-native-render-html#203]
How to judge the content is loaded, including images

**Comment by chrise86** [comment]
I'm facing an issue where the images stay as the default (100x100) size and don't enlarge when loaded.

**Comment by armagedan** [comment]
> I'm facing an issue where the images stay as the default (100x100) size and don't enlarge when loaded.

@Exilz can we have a fix for this. I am having the same issue. My img tag is wrapped in a p tag currently. I am not sure whats wrong with it. Although my img tag has width and height set already which is 1920x1080

**Comment by jsamr** [comment]
@chrise86 @armagedan I think you are referring to an issue that will be fixed when PR #311 is merged.
@duansiyu We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
