### ISSUE TITLE
Replace data with custom

### ISSUE THREAD

**Issue by jjg77** [archriss/react-native-render-html#215]
How can I replace an anchor tag text, which is currently a unicode symbol, with a vector icon?  I can remove the current unicode text, but not sure how to insert the icon. 

```
alterData={(node) =>{
              let { parent, data } = node
              if(parent && parent.name === 'a' && /[^\u0000-\u00ff]/.test(data)){
                return " "
              }
            }}
```

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
