### ISSUE TITLE
Not displaying in testflight

### ISSUE THREAD

**Issue by hari7priya** [archriss/react-native-render-html#240]
Content inside HTML (import HTML from 'react-native-render-html')tag is not visible once after archive is made (on testflight or on simulator of xcode).

**Comment by adam-buckley** [comment]
I would fill out the bug report template to make sure this actually gets answered by the devs, but I have my apps working just fine in Testflight/simulator/etc with this library.

Make sure you've linked the react-native-render-html library as per the docs for iOS. If you're fetching data from a remote source, make sure your server is using SSL (https) otherwise iOS will reject the request.

It's hard to provide help and suggestions without more context/code.

**Comment by Exilz** [comment]
#
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
