### ISSUE TITLE
How to convert new lines to line breaks or paragraph tags?

### ISSUE THREAD

**Issue by olinations** [archriss/react-native-render-html#255]
I have html that is one long block of text in one big p tag, but each paragraph within that p tag is on a new line instead of in another p tag. Is there a way I can convert a new line to a br tag or p tag?

Update:
Nevermind, it looks like this won't work and you knew that. I edited the HTML.js file and removed the part that ignores \r\n and it worked for part of the file, but other parts it made things much worse. I don't know what to do but I will keep working on it. PS - I hate Wordpress! (this is stemming from the wordpress API for their posts)

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
