### ISSUE TITLE
onLinkPress does not work for iframe links.

### ISSUE THREAD

**Issue by manzoorwanijk** [archriss/react-native-render-html#258]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I tested on Android, not sure about iOS.

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

React: 16.5.0
    React native: 0.57.0
    react-native-render-html: 4.1.2

  Target Platform:
    Android (9.0)

### Steps to Reproduce

(Write your steps here:)

1. Create HTML component with an iframe which has a link
2. Use `onLinkPress={(event, href) => Linking.openURL(href)}` (`Linking` from RN obviously)
3. Click on the link in the iframe.

### Expected Behavior

The link should open in a browser.

### Actual Behavior

Nothing happens

I tried with a downloadable SoundCloud track
`<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/191509820&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>`

When I click on the download button 👇🏻
![image](https://user-images.githubusercontent.com/18226415/56411962-37aec200-62a0-11e9-9950-85d2c6936819.png)

**Comment by jsamr** [comment]
@manzoorwanijk This is because the `iframe` tag [is rendered with a `WebView`](https://github.com/archriss/react-native-render-html/blob/40b0e591ff80799666964ed31e7af91a5afade9c/src/HTMLRenderers.js#L115).

@Exilz I support this in [`react-native-render-html-table-bridge`](https://github.com/jsamr/react-native-render-html-table-bridge).
To understand implementation, see [`HTMLTable::handleOnMessage`](https://github.com/jsamr/react-native-render-html-table-bridge/blob/master/src/HTMLTable/index.tsx#L109) method and the [injected script](https://github.com/jsamr/react-native-render-html-table-bridge/blob/master/src/HTMLTable/script.ts#L27).

If you are interested, I could refactor the surface area related to communicating with the `WebView` to an intermediary component which would have `onLinkPress` and `onHeightUpdate` callbacks and publish it on npm. I could also add some guard-code in the injected script to support the legacy core `WebView` component.

`react-native-render-html-table-bridge` only support [community version](https://github.com/react-native-community/react-native-webview) ATM.

**As a side note**: because of the deprecation of core component, you should probably require users to provide their own version of `WebView` component, or instruct them to manually install and link the library.

**Comment by hadi13** [comment]
also links are not working with me !!

**Comment by jsamr** [comment]
This feature has been shipped in the new [@native-html/iframe-plugin](https://github.com/native-html/plugins/tree/master/packages/iframe-plugin#readme) package, ready for react-native-render-html v5.0.0. Thank you for your contribution!
