### ISSUE TITLE
I wonder if the component shows math formula in html

### ISSUE THREAD

**Issue by saeedtkh** [archriss/react-native-render-html#280]
I would like to have the following html rendering in react native using your component. How ever doesn't show correctly. 

(<i>a</i> + <i>b</i> + √<i>c</i>)<sup>2<i>x</i> + <i>b</i></sup>

Any idea?

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html`  tag. We are notified on this tag, and will be happy to help you here.
