### ISSUE TITLE
Remove the parent and return new node. [Help Wanted]

### ISSUE THREAD

**Issue by kamalpandey** [archriss/react-native-render-html#294]
Can some help with 

``` 
   <ol start="1">
      <li><h3>Test 1</h3></li>
   </ol>
   <ol start="2">
       <li><h3>Test 2</h3></li>
   </ol>

``` 

What it is giving me is

```
1)
   Test 1

1)
  Test 2

```

What I want is

``` 
1. Test 1
2. Test 2
```

How should i return this?

```
      <h3>1. Test 1</h3>
      <h3>2. Test 2</h3>
 
```

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.

As per the start feature, it is not supported yet, but there is a workaround, see #336
