### ISSUE TITLE
Two nested img tag not in row as html default

### ISSUE THREAD

**Issue by tuannguyenhoangit-droid** [archriss/react-native-render-html#307]
In html like that
<img width="826" alt="Screen Shot 2019-10-16 at 10 06 29 PM" src="https://user-images.githubusercontent.com/56645054/66932505-eec6a300-f061-11e9-82ca-00df68a0d1b3.png">

But it isn't working in react-native-render-html, two image always is in new row

**Comment by choukat** [comment]
I have the same problem, did you fix it ?

**Comment by xuezhimin** [comment]
I have the same problem, did you fix it ?

**Comment by jsamr** [comment]
This is a limitation of the library: block elements cannot be displayed inline. We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
