### ISSUE TITLE
Questions on using this library to fit our use cases

### ISSUE THREAD

**Issue by aashishbarnwal** [archriss/react-native-render-html#309]
### Questions on using this library to fit our use cases

I have been trying to understand the feasibility of rendering a HTML with CSS styling in Android/iOS. To give some background, we have web presence where based on some user actions, the HTML is generated and rendered. The HTML contains CSS styles, attributes, tags (div/span/a/svg/path/button), anchor with url and mailto protocol, custom classes, so on and so forth.
The goal is to have good visual fidelity, great performance, code reuse and less maintenance.

Can you please help me with following questions?
1. RN supports only a fraction of CSS styles (~50%). Does it mean that there would good amount of gap in visual fidelity on mobile as compared to web?
2. Does this library support div/span/button/anchor tags? If yes, how are these being translated to RN components? Will we need to handle button/anchor clicks on our own?

**Comment by giacomocerquone** [comment]
@aashishbarnwal well actually your questions are even out of the scope of this package, but I'll try to anwser to your doubts.

1. Yes, it's true, lots of css styles aren't supported and you'll have a hard time implementing certain small UI details (shadows for example).
But you must consider that web pages and mobile apps are clearly two different platforms where the styling gets applied and honestly if you need to build an app graphically identically to a website, there are problems in your project since a mobile app would require a different design (necessarily).
So, if you're asking if React Native is mature enough related to styling an app, I will say yes it is.

2. This library doesn't give you anithying to enhance the styling of a React Native app (just to be clear) and div, span, button and anchor are of course supported and translated into View, Text, TouchableNativeFeedback, TouchableHighlight (I might be wrong on the conversions but you'll surely find a table in the readme)

**Comment by jsamr** [comment]
I am closing because this issue seems to have been resolved.
