### ISSUE TITLE
Error whie updating property 'display' in shadow  node of type:RCTImageView

### ISSUE THREAD

**Issue by yrjwcharm** [archriss/react-native-render-html#317]
![image](https://user-images.githubusercontent.com/34397383/69021273-3d18ea00-09f2-11ea-96eb-107b433c6f7a.png)

**Comment by yrjwcharm** [comment]
HTML has  'display'    word   is  error

**Comment by yrjwcharm** [comment]
Big Boss
 help!!!

**Comment by ThanhNguyen140797** [comment]
same error

**Comment by yrjwcharm** [comment]
@ThanhNguyen140797  react-native-htmlview 这个库可以解决这个问题。

**Comment by a5740** [comment]
Just add 'display' in ignoredStyles.

Ex.:
ignoredStyles={['font-family', 'display']}
#257

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
