### ISSUE TITLE
Is it support on popup?

### ISSUE THREAD

**Issue by harleenarora** [archriss/react-native-render-html#320]
I have HTML data and this data got by my custom API and I tried to display this HTML on a popup. But WebView is not working on popup. Is it working on popup?

**Comment by chrissnape** [comment]
Do you mean a modal? I have got text to display, but I'm trying to use an iframe vimeo player, it works elsewhere in the app, but it's not displaying in a modal for some reason.

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
