### ISSUE TITLE
ENOENT: no such file or directory.

### ISSUE THREAD

**Issue by Skylnt** [archriss/react-native-render-html#324]
ENOENT: no such file or directory, scandir '*\node_modules\htmlparser2\lib\node_modules\entities\maps'. I use with Expo. Please help me.

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html`  tag. We are notified on this tag, and will be happy to help you here.
