### ISSUE TITLE
Style is not working?

### ISSUE THREAD

**Issue by harleenarora** [archriss/react-native-render-html#331]
I have add style on top on the render html like this, 

```
<View style={[textCenter, labelTitle, labelStyle]}>
	<HTML
		html={secData.settings.gallery.title.content}
	/>
</View>
```

But View css ki not working.

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html`  tag. We are notified on this tag, and will be happy to help you here.
