### ISSUE TITLE
Strange background image behind custom rendered component

### ISSUE THREAD

**Issue by FrancisLeigh** [archriss/react-native-render-html#339]
I have a custom element called `<coin />` which is rendered via
```
renderers={{
    coin: {
        renderer: () => (
            <Image
                source={require("../../assets/iconography/currency.png")}
                style={styles.coinsIcon}
            />
        ),
        wrapper: "Text",
    },
}}

// styles
height: 16,
width: 16,
```
This all renders fine apart from a strange background image of what looks like a "file" icon (see attached) - has anyone seen this before? 
<img width="111" alt="Screenshot 2020-02-07 at 17 21 58" src="https://user-images.githubusercontent.com/10357801/74051045-24a3e480-49cf-11ea-86b3-cb8a9e64c526.png">

**Comment by FrancisLeigh** [comment]
^

**Comment by danvee** [comment]
Also having this issue.

Appears to affect iOS devices only. Not present on iOS10 but presents on 13.x

**Comment by jsamr** [comment]
@FrancisLeigh Likely a React Native bug. We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
