### ISSUE TITLE
Need help with nested markup

### ISSUE THREAD

**Issue by jotamimoso** [archriss/react-native-render-html#34]
Hi, I'm having a bit of trouble while trying to render this markup:

```
<p class="textNormal">
    Classifica a afirmação como verdadeira ou falsa.
</p>
<p class="textNormal">
    <p class="textItalic">
        Na potência
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAAYCAYAAAAcYhYyAAACKUlEQVQ4T9WUPYgTURSFz32JEwKZ8acSW4MIQSHzCBIb04laiFqIFluo4F9joazCsrgKslvqdoI2Cq5a+ceigo5aBDJvHmHwBxWFLWzsZLIqM5O5MpINu7CbRN3Gqe/75pxzz3uEZfhoGRgYCFKr1bJBEBwHsAnAFgDTAC54nvc9FTEQpFKpbEuS5GQ2mz0Sx3ERwANmHtNaXx0YYtv2HiKaZObdRDQD4CGA96ZpHnUc52dXiZRyIxGdT5JkloiqzPwyjuNR3/e/zs/Ntu3NRHSfmUe01je7Ssrl8joiupv61Fo/7gxOE9GrMAwP+74/mw6XSqVCPp+/AuBToVCYcBwn7kI6nh0Az8Mw3GcYRqYjeS0z79Bav0vDbbVaw0mSfLEsayoIArEgWCnlegD3ALwAcCaKooJhGI+Y2QKw0zTNmSAIzgH4liTJLSLaJYQQSqnrSwYrpUzX+BTAFIBTzLydiG4DWDGXDxENKaVuLAqpVqtroii6zMwbhBCHXNd906+QC3qSrhKAJKKtAJ5EUTQ5F2ov0KJlS9WEYZhua3W73d7fbDY/9oVIKVcyczGXy72t1+s/0gNSynEAwwBGPc+72BPSuRfXAAwBmPA87+x8CBGNKKUuAeClQL/tSClPADhGRAeVUq/T8gkh7gBYlclk9jYajQ997RSLxZxlWQeI6DSAEEDaj2dCiHHXdT//0Xb6Dfe087eHu8X7V8DA70m/Hw30sv0/kF/YJNkZw95t5QAAAABJRU5ErkJggg=="></img>
        , ao 
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAUCAYAAAC07qxWAAABb0lEQVQ4T8WSO0sDQRhF7zeRTSPxUYmti1gJ2SFIbEyrnVqIFhbaiJWFooUEUZBYirW9aCUoooLPIpDdWcLiAxT9AbYhCjPJjuziBiERY+XUZy5z7lxCk4ea5FADOed9RLTm+36ZiNJa65tKpZL1PO8tCAvBZDLZTUQHANZd1z21LKufiE6I6FZKOet5XjkEU6nUkO/7VwAupZTjhmHEABwB6NJaD7uu+xiCnPMeAIcArgEsKaVaDcM41lonAIwIIV4aynDOBwCcA9gDsCCEeK8D0+l0p1JqW2vdyxibsW37viYTVWRZ1mjwEiIaBHCmlNoJROrA6EKQKqUMWuioVqsTxWLxOZJp01qb8Xj8IZ/Pf3wJ5gAsA8gKITYok8m0lEqlXQDTALaEECvfQSJadRxnM0qcBzBHRFOO49wFH8AY2wfQHovFxgqFwlMImqYZTyQSk0S0CEACCPq7YIzlbNt+/VGm0VD+vp7f5vaPiZ+46IsWimqlqwAAAABJRU5ErkJggg=="></img>
        chamamos base e ao 
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAUCAYAAAC07qxWAAABWUlEQVQ4T9WSvUoDQRSFz511ZQLbaCEo+AQLgexkizSilRAbC2s7bRQsBQ02itgG/IEI/jQ22uQJDKkkuzuVNiG+Q9IIG2SuTDBbxICxdNr55rucM5cw4aEJOWRgoVBYEEKcAlgCMEVEFc/zHhqNxqeVDcBSqTTb7/dvmPkqTdNnKeUhgCMLx3FsH/MALBaLG8y8BmAnSZIPa3ccp87MM47jlFutVnsAKqWOAVS+wUvf96ellOcAtohoPY7j+tC4accy867W+s6OUkqdAdhn5m2t9fXY1L7ve7lc7p6ZV5i5rLV+GQsGQbBKRI8Aqr1e76TT6aQ/wDAMfWPMExHddrvdqoWyeoalh2G4yMw1Y0xNa11XSkl7Z5vIjEqpeQAXQohqFEVNGygIggMhxFuWOp/Pz7muWwNgALxaCIBLRMtEtBdFUTTa4+jXtwGUkyR5//tS/LZF/8H4BXYBjRU2RJ5mAAAAAElFTkSuQmCC"></img>
        chamamos expoente.
     </p>
</p>
```

This is what I'm getting:

![screenshot_2017-10-12-11-09-34](https://user-images.githubusercontent.com/15654564/31491445-3caf555a-af3f-11e7-9a83-1733d3d40074.png)

What I'm targeting is having the second `<p>` break line as it is, but the next images and text to keep inline, instead of breaking line and to keep the styles as it is not applying any.
Can't seem to understand why it is happening, and any help will be appreciated.
Thank J.

**Comment by Exilz** [comment]
Hi,
this is kind of expected. A huge problem with rendering HTML with native components is wrapping `View` inside `Text`.
Since `<img>` is a "block" element, the wrapper around your `<p>` *has* to be one too to prevent rendering a `View` without height and width inside a `Text`, which would make react-native crash.
These `View` wrappers rendered one after the other cause the line breaks.

A nice improvement to the renderer would be to flag some images that shuld be rendered inline, but sadly, until react-native improves, there is no way to render the HTML the way you'd like without changing your markup and adding some kind of prop to render your images inline.

I hope this enlightens you !

**Comment by jotamimoso** [comment]
Oh I see now! I've managed to get it to look as I wanted tho. I just added flexDirection: 'row' and flexWrap: 'wrap' to the wrapping views and they r inline now. 
Thanks for the tips and for this great package. Been very helpfull. 

Thanks J.

**Comment by Exilz** [comment]
I'm happy to see you've found a solution 😄 . The only problem is that we're relying on styling that wouldn't be needed on a browser, but heh, good enough I guess ¯\_(ツ)_/¯

**Comment by jotamimoso** [comment]
Ye that's true. I've now tried with different markups (that have different nested tags) and its working, so I guess its good for now.

**Comment by harrison0723** [comment]
The problem with `flexDirection: 'row'` + `flexWrap: 'wrap'` is that when you have too many text before or after each image, the `<Text>` box would wrap the text as well, making it unreadable. OP's example included very little text which is why it worked. Mind has more text, and I'm still trying to find a workaround... anybody has any suggestions?
