### ISSUE TITLE
Cannot render .svg image on Html img tag, but .png can be

### ISSUE THREAD

**Issue by kienphan** [archriss/react-native-render-html#358]
Same as title, I saw that my html include .svg img link is not rendered, but .png link was.

**Comment by jsamr** [comment]
React Native Image component does not support svg files. Your only chance is to define a [custom renderer](https://github.com/archriss/react-native-render-html#creating-custom-renderers) which supports svg rendering through third parties like [react-native-svg](https://github.com/react-native-community/react-native-svg). We might consider support for svg in the future though. I'm closing because this issue did not comply with our [contribution guidelines](https://github.com/react-native-community/react-native-svg/blob/develop/CONTRIBUTING.md).
