### ISSUE TITLE
Select first paragraph

### ISSUE THREAD

**Issue by tarifaljnidi** [archriss/react-native-render-html#367]
### Is this a bug report or a feature request?
Question (maybe feature request?)

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

(yes)

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

(yes)

### Have you made sure that your issue hasn't already been reported/solved?

(yes.)
### Environment

React: 16.11.0
React native: 0.62.0
react-native-render-html: 4.2.0

### Explanation
Hello, I am trying to get first and second paragraphs to apply number of lines, this code gives me all of them:

The code :
```
  <View style={{width:Dimensions.get('window').width-30}}>
  <HTML html={htmlContent}
  renderers={{
  p :(_, children) => <Text  numberOfLines={2}  >{children}</Text>
}}
   tagsStyles={{
       p:{
   marginBottom:20,
  fontSize:16
  }
 }}
   />
</View>
``` 
I tried this also, but I don'not know how to get the first or second child:
``` 
renderers={{
     p: (htmlAttribs, node, parent, children, innerHTML) => {
         if (htmlAttribs.class == "text") {
        <Text  numberOfLines={2}  >{children.rawChildren[0].data}</Text>
        }
      }
}}
```

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add  the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.

Friendly remark: your missing a return statement in the second snippet; you're not returning the Text element.
