### ISSUE TITLE
<OBJECT /> DOES NOT WORK

### ISSUE THREAD

**Issue by Gardens18** [archriss/react-native-render-html#368]
html5 OBJECT tag with data="https://webaite.com/index.html" DOES NOT WORK

please support

**Comment by Gardens18** [comment]
Any support on this ?

**Comment by jsamr** [comment]
This library does not claim support for `<object>` tags. Objects are very versatile, and thus would require an embedded WebView. We might consider supporting it in the future though. I am closing because this issue did not comply with the [contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md).
