### ISSUE TITLE
hi everyone,i want to custom fontsize and font face, can you help me

### ISSUE THREAD

**Issue by Hieu1906** [archriss/react-native-render-html#374]
### Is this a bug report or a feature request?

(Write your answer here.)

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

(Write your answer here.)

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

(Write your answer here.)

### Have you made sure that your issue hasn't already been reported/solved?

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by kaiyes** [comment]
Use  `baseFontStyle={{ fontFamily: "your font here"  }}` . So it's gonna look like 

`<HTML` html={post} baseFontStyle={styles.paragraph} />`

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add   the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
