### ISSUE TITLE
how to open phone app or email on click from html content which contains phone number or email?

### ISSUE THREAD

**Issue by reactdevrocks** [archriss/react-native-render-html#376]
i have html contents coming from api.

```
<HTML
              html={this.state.htmlContent1}
              imagesMaxWidth={Dimensions.get('window').width}
            />
```

**Comment by reactdevrocks** [comment]
so if html content has a phone number or email then how can i open phone app or email app by clicking on them?

**Comment by jsamr** [comment]
@reactdevrocks We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow our guidelines, it will be closed. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
