### ISSUE TITLE
Ordered list with child unordered list renders odd numbers only

### ISSUE THREAD

**Issue by jeloagnasin** [archriss/react-native-render-html#396]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report

When an ordered list (`<ol>`) has unordered list (`<ul>`) children, the numbers get messed up.

#### Reproduction

https://snack.expo.io/@bldai/rnrhtml-template

##### Description

Please see attached snack to reproduce the issue. If the same HTML file is rendered on Chrome, it renders properly the numbers properly. I'm expecting that it should follow the same behavior.

##### Reproducible Demo

https://snack.expo.io/@bldai/rnrhtml-template

**Comment by jsamr** [comment]
@jeloagnasin Thank your taking the time to provide a high-quality report!

The snippet that you provided is not valid HTML, because `ul` is not allowed as children of `ol`. To perform the validation check with w3 tool, copy paste the bellow snippet in the box at this [w3c online check tool](https://validator.w3.org/). Select "Validate fragment" with "HTML4", and you'll see errors like:

![2020-07-31-065334_1129x248_scrot](https://user-images.githubusercontent.com/3646758/89023871-a0d21180-d2fa-11ea-9a7f-178e05947647.png)

You can also select full validation option with HTML5, and the same error arise. While browsers might try to do a big endeavor to make it look a bit better, the behavior of this library when receiving invalid HTML is unpredictable! We should add a caution note on this subject, and direct users to validation tools :-).

```html
<ol>
  <li>First item</li>
  <ul>
    <li>Sub item 1</li>
    <li>Sub item 2</li>
  </ul>
  <li>Second item</li>
  <ul>
    <li>Sub item 1</li>
  </ul>
</ol>
```

**Comment by jsamr** [comment]
A valid snippet would be

```html
<ol>
  <li>
    First item
    <ul>
      <li>Sub item 1</li>
      <li>Sub item 2</li>
    </ul>
  </li>
  <li>
    Second item
    <ul>
      <li>Sub item 1</li>
    </ul>
  </li>
</ol>
```
