### ISSUE TITLE
Error when inspecting with Expo: "Expected to find at least one React Renderer"

### ISSUE THREAD

**Issue by hi019** [archriss/react-native-render-html#402]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [see below] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report
When inspecting the default exported `HTML` element on Expo Android, I get "Expected to find at least one React renderer."

#### Libraries 

react-native-render-html: 4.2.3
react-native-webview: "*"

#### Devices

- Device 1: Oneplus 7T
  * OS: Android 10
  * Diagnostic:  reproduction
  * Environment: development

Unfortunately I only have access to this device right now. 

#### Reproduction
1. Download, install and `yarn start` https://snack.expo.io/jIqtdd1I9
2. Connect via Expo app by scanning QR code displayed on `yarn start`
3. Shake device to open bottom menu > Toggle Element Inspector 
4. Click `Hello world` (make sure you are not selecting the view)

You should see a red React error screen with `Expected to find at least one React renderer.`

Note this is probably a duplicate of #230, but the issues linked are closed. Also, if you replace the `HTML` element with `Text` it works fine.

**Comment by jsamr** [comment]
@hi019 First of all, thank you for your effort to make a good quality, detailed report compliant with our guidelines. React Native housekeeping policies are very annoying, because they use the "stale" bot to bury issues into oblivion. **So keep in mind: if an issue is closed in the react native issue tracker, it is no hint that the problem has been fixed.** We're not doing black magic in this library code, just rendering a plain old react tree. I will take the time to inspect your peculiar example, but as mentioned in the referred issue #230, I consider the bug upstream.

**Comment by hi019** [comment]
I understand. Maybe I'll try to create a reproduction without this library and create a React issue.
