### ISSUE TITLE
Click to open url

### ISSUE THREAD

**Issue by vinhtran6921** [archriss/react-native-render-html#433]
I cant click to open url. How can I implement function class openURL ?
Thanks for your help

> const html = `<p style="color: #373737; line-height: 18px; font-size: 0.75rem; letter-spacing: 0.1px;">Kichi-Kichi to&agrave;n quốc, xem danh s&aacute;ch <a class="openURL"> <span id="https://google.com.vn">tại đ&acirc;y</span> </a>.</p>`;

Also when font-size is 0.75rem it not show. Maybe "rem" isn't support

**Comment by jsamr** [comment]
@vinhtran6921 As per your questions:

1. To implement custom renderers, you can use renderers prop, see [Creating custom renderers](https://github.com/archriss/react-native-render-html#creating-custom-renderers);
2. `rem` are not supported in the v4 and v5, but is supported in v6, which first prerelease will be available today, see #430 

I am closing because this report does not follow our guidelines. Feel free to comment here or [on Discord](https://discord.gg/dbEMMJM) for assistance.
