### ISSUE TITLE
Styling lists

### ISSUE THREAD

**Issue by wayferer** [archriss/react-native-render-html#48]
Hi there,

Can I ask if there is a reason for the `paddingLeft: 20` located here: https://github.com/archriss/react-native-render-html/blob/master/src/HTMLRenderers.js#L100

I can't seem to find a way to overwrite it. Will I need to make use of `listsPrefixesRenderers` to do so?

Thanks.

**Comment by Exilz** [comment]
Hi,
unless you provide your own `ul` and/or `ol` renderers, you won't be able to change this value.

It's there to render the list with a slight offset to the left.

`listsPrefixesRenderers` won't change much, since it renders the prefix that is inside each `children` being rendered inside the `View` that receives this style.

**Comment by wayferer** [comment]
I see. Thank you for your response, I'll give that a go.
