### ISSUE TITLE
issue rendering HTML

### ISSUE THREAD

**Issue by cinder92** [archriss/react-native-render-html#62]
Hello i have this html

```
<p>Alrededor de las 12:45 horas los usuarios de la aplicaci&oacute;n empezaron a reportar la ca&iacute;da del servicio en redes sociales como Twitter, algunos molestos y otros tom&aacute;ndolo con humor.<br /><br />Esta es la segunda ocasi&oacute;n en la que el servicio de WhatsApp sufre una ca&iacute;da en el mes. El 3 de noviembre WhatsApp sufri&oacute; una ca&iacute;da desde alrededor de las 05:00 horas y hasta las 07:00. Dicha ca&iacute;da se suscit&oacute; en diversos pa&iacute;ses de Asia, Europa y el continente americano.<br /><br />WhatsApp ha enfrentado ca&iacute;das generalizadas similares este a&ntilde;o, incluyendo una de varias horas en mayo.<br /><br />El servicio de mensajer&iacute;a es usado por m&aacute;s de mil 200 millones de personas en todo el mundo y es una herramienta clave de comunicaciones y comercio en muchos pa&iacute;ses.</p>
<p>El servicio se restableci&oacute; a la 1:17 de la tarde.</p>
```
The first `<p>` is not rendering with the next code, only the second one

```
<HTML 
  ...
  'p' : {
      fontSize: 18
      color: "black",
      paddingBottom : 15
   },
/>
```

EDIT.

if i used
`ignoredTags={['br']}`

im getting this error

![captura de pantalla 2017-11-30 a la s 14 00 41](https://user-images.githubusercontent.com/4725556/33452162-e563bbce-d5d6-11e7-902c-b198f47094d3.jpg)

any idea whats happening?

**Comment by Exilz** [comment]
Hi, your snippet is working fine for me. Both with the ignored br node and without.

Are you sure you're rendering this exact html ? Because from the screenshot you linked, it looks like you're rendering something with the style `"display: block"`, which doesn't work by default with react-native.

This is another issue by itself, and it's been reported for various CSS properties, such as #66

If it's actually crashing with this sample of HTML, tell me and I'll re open the issue and investigate furthermore.
