### ISSUE TITLE
How can I limit the HTML height?

### ISSUE THREAD

**Issue by KlimczakM** [archriss/react-native-render-html#98]
I try to limit the HTML height

 ```
<View style={styles.articleContent}>
    <HTML
        html={this.props.article.content}
        imagesMaxWidth={Dimensions.get('window').width}
        onLinkPress={(evt, href) => this.onLinkPress(href)}
    />
</View>

articleContent: {
    height: 100,
    backgroundColor: 'blue'
} as ViewStyle
```

but it doesn't work, it fills the whole space and if it's not enough, a scroll that I cannot disable appears. How can I achieve this?

**Comment by baona95** [comment]
Maybe you could try `containerStyle` prop

**Comment by KlimczakM** [comment]
Thank you for your reply. Unfortunately, it didn't work:

```
<HTML
    html={content}
    imagesMaxWidth={imagesMaxWidth}
    onLinkPress={(evt, href) => this.onLinkPress(href)}
    containerStyle={styles.container}
/>

container: {
    height: 300,
} as ViewStyle
```

**Comment by Exilz** [comment]
Hi,
both of the solutions you tried are working for me (the `View` wrapper, and `containerStyle`).
Moreover, there are no `ScrollView` in this module, if a scrolling indicator appears, it must be on your side.

I guess the problem is on your side. Don't forget the `customWrapper` prop if you need to customize your rendering even more.
